"""init schema

Revision ID: 811b7b0363d6
Revises: 
Create Date: 2025-12-27 10:52:39.574022

"""
from alembic import op
import sqlalchemy as sa


revision = '811b7b0363d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('request_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('is_scrap', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('warranty_vendor', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_team_id', sa.Integer(), nullable=False),
    sa.Column('default_technician_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('unusable_reason', sa.Text(), nullable=True),
    sa.Column('unusable_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(department_id IS NOT NULL) OR (owner_user_id IS NOT NULL)', name='equipment_owner_check'),
    sa.ForeignKeyConstraint(['category_id'], ['equipment_category.id'], ),
    sa.ForeignKeyConstraint(['default_technician_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['maintenance_team_id'], ['maintenance_team.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('idx_equipment_team', 'equipment', ['maintenance_team_id'], unique=False)
    op.create_table('maintenance_team_member',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['maintenance_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_table('maintenance_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('equipment_category_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_duration_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('repaired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("request_type IN ('corrective','preventive')", name='request_type_check'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['equipment_category_id'], ['equipment_category.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['request_stage.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['maintenance_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_req_equipment', 'maintenance_request', ['equipment_id'], unique=False)
    op.create_index('idx_req_scheduled', 'maintenance_request', ['scheduled_start'], unique=False)
    op.create_index('idx_req_stage', 'maintenance_request', ['stage_id'], unique=False)
    op.create_index('idx_req_team_stage', 'maintenance_request', ['team_id', 'stage_id'], unique=False)
    op.create_table('maintenance_request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_request_log')
    op.drop_index('idx_req_team_stage', table_name='maintenance_request')
    op.drop_index('idx_req_stage', table_name='maintenance_request')
    op.drop_index('idx_req_scheduled', table_name='maintenance_request')
    op.drop_index('idx_req_equipment', table_name='maintenance_request')
    op.drop_table('maintenance_request')
    op.drop_table('maintenance_team_member')
    op.drop_index('idx_equipment_team', table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('request_stage')
    op.drop_table('maintenance_team')
    op.drop_table('location')
    op.drop_table('equipment_category')
    op.drop_table('department')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
