"""init schema

Revision ID: 8562ca7f8964
Revises: ebad60a82b0d
Create Date: 2025-12-27 11:19:28.832506

"""
from alembic import op
import sqlalchemy as sa


revision = '8562ca7f8964'
down_revision = 'ebad60a82b0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
