"""init schema

Revision ID: ebad60a82b0d
Revises: 811b7b0363d6
Create Date: 2025-12-27 11:12:20.208938

"""
from alembic import op
import sqlalchemy as sa


revision = 'ebad60a82b0d'
down_revision = '811b7b0363d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
